# Python 101: List, NumPy Array, and DataFrame

For introductory data analysis and machine learning, three Python objects are especially useful:

| Object | Main idea | Typical use |
|---|---|---|
| **Python list** | General-purpose container | Store a collection of objects |
| **NumPy array** | Numerical array | Vectors, matrices, numerical computation |
| **pandas DataFrame** | Labeled table | Datasets with rows and named columns |

A useful progression is

$$
\boxed{
\text{Python list}
\;\longrightarrow\;
\text{NumPy array}
\;\longrightarrow\;
\text{DataFrame}
}
$$

## 1. Python List

A **list** stores several objects in one variable.

Lists use square brackets:

```python
x = [10, 20, 30]
```

Python starts counting positions at `0`.

In [1]:
x = [10, 20, 30]

print(x)
print(type(x))
print("First element:", x[0])
print("Second element:", x[1])
print("Last element:", x[-1])

[10, 20, 30]
<class 'list'>
First element: 10
Second element: 20
Last element: 30

### Lists are flexible

A Python list can contain different types of objects at the same time.

In [2]:
a = [1, "hello", 3.5]

print(a)

[1, 'hello', 3.5]

Here the same list contains an integer, a string, and a floating-point number.

This flexibility makes lists useful as **general-purpose containers**.

### List arithmetic

For ordinary Python lists, `+` does **not** mean coordinate-wise addition.

For example:

In [3]:
a_list = [1, 2]
b_list = [3, 4]

print(a_list + b_list)

[1, 2, 3, 4]

The output is

```text
[1, 2, 3, 4]
```

because `+` **concatenates** the two lists.

If we want coordinate-wise addition,

$$
[1,2] + [3,4]
\quad\longrightarrow\quad
[1+3,\;2+4]
=
[4,6],
$$

we can write it explicitly using `zip()`.

In [4]:
a_list = [1, 2]
b_list = [3, 4]

c_list = [a + b for a, b in zip(a_list, b_list)]

print(c_list)

[4, 6]

## 2. NumPy Array

A **NumPy array** is designed for numerical computation.

First import NumPy:

```python
import numpy as np
```

Then create an array with `np.array()`.

In [5]:
import numpy as np

a = np.array([1, 2, 3])

print(a)
print(type(a))
print("shape:", a.shape)
print("number of dimensions:", a.ndim)

[1 2 3]
<class 'numpy.ndarray'>
shape: (3,)
number of dimensions: 1

For this example,

```python
a.shape
# (3,)
```

means that the array has three elements along its one dimension.

```python
a.ndim
# 1
```

means that it is a **one-dimensional array**.

### Why NumPy arrays are useful

Numerical operations are naturally performed coordinate by coordinate.

In [6]:
a = np.array([1, 2])
b = np.array([3, 4])

print("a + b =", a + b)
print("a * 2 =", a * 2)
print("a squared =", a**2)

a + b = [4 6]
a * 2 = [2 4]
a squared = [1 4]

So, unlike Python lists,

```python
np.array([1, 2]) + np.array([3, 4])
```

gives

```text
[4 6]
```

directly.

This is one major reason NumPy arrays are useful for economics, statistics, and machine learning.

### Dimensions of a NumPy array

A NumPy array can have one, two, three, or more dimensions.

$$
\begin{aligned}
\text{1D array} &\approx \text{vector},\\
\text{2D array} &\approx \text{matrix},\\
\text{3D array} &\approx \text{stack of matrices}.
\end{aligned}
$$

The number of dimensions tells us how many coordinates are needed to locate one element.

### 1D array: vector-like

```python
a = np.array([1, 2, 3])
```

has

```python
a.shape
# (3,)
```

and

```python
a.ndim
# 1
```

### 2D array: matrix

```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

represents

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}.
$$

Its shape is

```python
A.shape
# (2, 3)
```

so

$$
\boxed{\text{2D shape}=(\text{rows},\text{columns})}.
$$

In [7]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A)
print("shape:", A.shape)
print("ndim:", A.ndim)

print("A[0, 1] =", A[0, 1])
print("First row:", A[0, :])
print("Second column:", A[:, 1])

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
A[0, 1] = 2
First row: [1 2 3]
Second column: [2 5]

For a 2D array,

```python
A[row, column]
```

selects an element.

For example,

```python
A[0, 1]
```

means **row 0, column 1**.

### 3D array: stack of matrices

A 3D array can be viewed as several 2D matrices stacked together.

```python
B = np.array([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])
```

Here,

```python
B.shape
# (2, 2, 2)
```

can be read as

$$
(\text{number of matrices},\text{rows},\text{columns}).
$$

In [8]:
B = np.array([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])

print(B)
print("shape:", B.shape)
print("ndim:", B.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)
ndim: 3

### NumPy arrays and matrices

A **2D NumPy array** is the standard way to represent a matrix in modern NumPy.

For example,

In [9]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Elementwise multiplication:")
print(A * B)

print("\nMatrix multiplication:")
print(A @ B)

Elementwise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]

Here:

- `A * B` performs **elementwise multiplication**;
- `A @ B` performs **matrix multiplication**.

## 3. pandas DataFrame

A **DataFrame** is a labeled table with rows and named columns.

It is especially useful for working with real datasets.

For example:

In [10]:
import pandas as pd

df = pd.DataFrame({
    "year": [2022, 2023, 2024],
    "gdp_growth": [1.9, 2.5, 2.8],
    "inflation": [8.0, 4.1, 2.9]
})

df

   year  gdp_growth  inflation
0  2022         1.9        8.0
1  2023         2.5        4.1
2  2024         2.8        2.9

Conceptually, the DataFrame looks like a table:

| year | gdp_growth | inflation |
|---:|---:|---:|
| 2022 | 1.9 | 8.0 |
| 2023 | 2.5 | 4.1 |
| 2024 | 2.8 | 2.9 |

A DataFrame has:

- **rows** = observations;
- **columns** = variables;
- **column names** = labels for the variables.

In [11]:
print(df.shape)
print(df.columns)

(3, 3)
Index(['year', 'gdp_growth', 'inflation'], dtype='str')

For this example,

```python
df.shape
# (3, 3)
```

means

$$
(\text{3 rows},\text{3 columns}).
$$

### Selecting DataFrame columns

We can select one column by its name.

In [12]:
df["gdp_growth"]

0    1.9
1    2.5
2    2.8
Name: gdp_growth, dtype: float64

We can also select several columns:

In [13]:
df[["year", "gdp_growth"]]

   year  gdp_growth
0  2022         1.9
1  2023         2.5
2  2024         2.8

### NumPy array vs. DataFrame

Both can represent rectangular numerical data, but they emphasize different things.

| Feature | NumPy array | DataFrame |
|---|---|---|
| Main purpose | Numerical computation | Data analysis |
| Column names | No | Yes |
| Row labels | No by default | Yes |
| Matrix operations | Excellent | Possible, but not its main purpose |
| Mixed column types | Limited | Yes |
| Common use | Math / ML computation | Real-world tabular datasets |

A useful way to think about them is:

$$
\boxed{
\text{NumPy array} \approx \text{numerical matrix}
}
$$

while

$$
\boxed{
\text{DataFrame} \approx \text{labeled dataset}
}
$$

## 4. Quick Summary

### Python list

```python
x = [1, 2, 3]
```

- general-purpose container;
- can contain different object types;
- `+` concatenates lists rather than performing vector addition.

### NumPy array

```python
x = np.array([1, 2, 3])
```

- designed for numerical computation;
- supports coordinate-wise arithmetic;
- 1D array $\approx$ vector;
- 2D array $\approx$ matrix;
- 3D array $\approx$ stack of matrices.

### pandas DataFrame

```python
df = pd.DataFrame(...)
```

- designed for tabular datasets;
- rows are observations;
- columns are variables;
- columns have names.

So the main distinction is

$$
\boxed{
\text{List: general container}
\qquad
\text{NumPy: numerical computation}
\qquad
\text{DataFrame: labeled dataset}
}
$$

## 5. Practice

### Practice 1 — Python list

Create two lists and calculate their coordinate-wise sum using `zip()`.

Follow the gray code below, then type it yourself in the blank code cell.

<div style="margin:6px 0 4px 0; font-size:0.92em; color:#777;"><b>Gray guide:</b></div>
<pre style="color:#aaaaaa !important; background:#f7f7f7; border:1px solid #e6e6e6; border-radius:5px; padding:10px 12px; line-height:1.45; font-size:13px; font-family:monospace;">a = [2, 4, 6]
b = [1, 3, 5]

c = [x + y for x, y in zip(a, b)]

print(c)</pre>

### Practice 2 — NumPy array

Create two NumPy arrays and calculate:

1. `a + b`
2. `a * 2`
3. `a**2`

Follow the gray code below, then type it yourself in the blank code cell.

<div style="margin:6px 0 4px 0; font-size:0.92em; color:#777;"><b>Gray guide:</b></div>
<pre style="color:#aaaaaa !important; background:#f7f7f7; border:1px solid #e6e6e6; border-radius:5px; padding:10px 12px; line-height:1.45; font-size:13px; font-family:monospace;">import numpy as np

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(&quot;a + b =&quot;, a + b)
print(&quot;a * 2 =&quot;, a * 2)
print(&quot;a squared =&quot;, a**2)</pre>

### Practice 3 — DataFrame

Create a DataFrame containing three observations and the columns:

- `year`
- `unemployment`
- `inflation`

Then print its shape and select the `inflation` column.

Follow the gray code below, then type it yourself in the blank code cell.

<div style="margin:6px 0 4px 0; font-size:0.92em; color:#777;"><b>Gray guide:</b></div>
<pre style="color:#aaaaaa !important; background:#f7f7f7; border:1px solid #e6e6e6; border-radius:5px; padding:10px 12px; line-height:1.45; font-size:13px; font-family:monospace;">import pandas as pd

df = pd.DataFrame({
    &quot;year&quot;: [2022, 2023, 2024],
    &quot;unemployment&quot;: [3.6, 3.6, 4.0],
    &quot;inflation&quot;: [8.0, 4.1, 2.9]
})

print(df)
print(&quot;\nShape:&quot;, df.shape)
print(&quot;\nInflation column:&quot;)
print(df[&quot;inflation&quot;])</pre>